test:p3:
  stage: test
  image: ubuntu:18.04
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qy
    - apt-get install -y python3 python3-dev python3-pip python3-numpy python3-scipy python3-matplotlib xvfb python3-setuptools python3-psutil python3-coverage
    - pip3 install hyperspy
    - pip3 install scipy --upgrade
    - pip3 install --user .
    #- xvfb-run python3 -m unittest discover -p test*.py ./
    - xvfb-run python3-coverage run -m unittest discover -p test*.py ./
    - python3-coverage report --include=*SQuEELS* --omit=*test* | tee coverage.txt
    artifacts:
        paths:
        - coverage.txt





pages:
  image: ubuntu:18.04
  stage: deploy
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip python3-numpy python3-scipy python3-matplotlib xvfb python3-setuptools python3-psutil
    - apt-get install -qy python3-sphinx python3-sphinx-rtd-theme build-essential
    - pip3 install hyperspy
    - pip3 install --user .
    - sphinx-apidoc -fT -o ./pages ./SQuEELS/ ./SQuEELS/tests
    - cd pages/
    - make html
    - cd ..
    - mv pages/_build/html public
  artifacts:
    paths:
      - public
  only:
    - master
