test:p3:
  image: ubuntu:18.04
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qy


pages:
  image: alpine:latest
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - pages
  only:
    - master
