language: python
python:
- '3.7'
install:
- pip install numpy scipy matplotlib tqdm hyperspy
- pip install sphinx sphinx-rtd-theme
- pip install --user .
script:
- python -m unittest discover -p test*.py ./
- sphinx-apidoc -fT -o ./pages ./SQuEELS/ ./SQuEELS/tests
- make -C pages/ html
- touch pages/_build/html/.nojekyll
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./pages/_build/html/
    keep_history: true