name: Python Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib hyperspy==1.5.1 pymc3 lmfit arviz tqdm unittest
    - name: Install SQuEELS package
      run : |
        pip install --user .
    - name: Run unit tests
      run: |
        xvfb-run python3 -m unittest discover -p test*.py ./